name: Node Setup
description: "Sets up Node JS for CI"

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Get pnpm store directory
      id: vars
      shell: bash
      run: |
        echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.vars.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Configures default env
      shell: bash
      run: |
        cp apps/web/.env.default apps/web/.env
        cp apps/cms/.env.default apps/cms/.env

    - name: Install
      shell: bash
      run: pnpm install
