---
# Areas
api:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**/*"

cms:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/cms/**/*"

web:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/web/**/*"

pwa:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/pwa/**/*"
api:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/pwa/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

pwa:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"

test:
  - changed-files:
      - any-glob-to-any-file:
        - "api/tests/**/*"
        - "apps/**/*.spec.ts"
        - "apps/**/*.test.ts"
        - "packages/**/*.spec.ts"
        - "packages/**/*.test.ts"
