name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    uses: paroki/portal/.github/workflows/testing.yml@ci
    secrets: inherit

  image:
    name: Image
    needs: ["testing"]
    if: github.event_name != 'pull_request'
    uses: paroki/portal/.github/workflows/image.yml@ci
    secrets: inherit

  gitlab:
    name: GitLab
    needs: ["testing", "image"]
    uses: paroki/portal/.github/workflows/gitlab.yml@ci
    secrets: inherit
