name: CI

on:
  push:
    branches:
      - next
      - debug
      - beta
      - main
      - wip
  pull_request:
    branches:
      - next
      - main

jobs:
  changes:
    name: Collect Changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.vars.outputs.api }}
      cms: ${{ steps.vars.outputs.cms }}
      web: ${{ steps.vars.outputs.web }}
      pwa: ${{ steps.vars.outputs.pwa }}
      node_test: ${{ steps.vars.outputs.node_test }}
      build_cms: ${{ steps.vars.outputs.build_cms }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect changes
        uses: ./.github/actions/collect-changes
        id: vars

  node-test:
    name: NodeJS
    needs: ["changes"]
    uses: paroki/pkrbt/.github/workflows/node-test.yml@next
    secrets: inherit
    with:
      node_test: ${{ needs.changes.outputs.node_test }}

  e2e:
    name: E2E
    needs: ["changes"]
    uses: paroki/pkrbt/.github/workflows/e2e.yml@next
    secrets: inherit
    with:
      node_test: ${{ needs.changes.outputs.node_test }}
      web: ${{ needs.changes.outputs.web }}

  build:
    name: Build
    needs: ["changes", "node-test", "e2e"]
    if: github.event_name != 'pull_request'
    uses: paroki/pkrbt/.github/workflows/image.yml@next
    secrets: inherit
    with:
      cms: ${{ needs.changes.outputs.build_cms }}

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request'
    needs: ["changes", "e2e"]
    uses: paroki/pkrbt/.github/workflows/deploy.yml@next
    secrets: inherit
    with:
      web: ${{ needs.changes.outputs.web}}
      pwa: ${{ needs.changes.outputs.pwa}}
