name: Deploy

on:
  workflow_call:
    inputs:
      web:
        type: string
        description: Deploy website
        required: true
      pwa:
        type: string
        description: Deploy website
        required: true

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_REMOTE_ONLY: true
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
jobs:
  web:
    name: Website
    if: inputs.web == 'true'
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest
          npm install -g turbo

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          pnpm install --filter=@pkrbt/web
          pnpm build --filter=@pkrbt/web
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
