name: E2E Testing

on:
  workflow_call:
    inputs:
      node_test:
        type: string
        description: Runs node test
        default: "false"
      web:
        type: string
        description: Runs web test
        default: "false"

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  web:
    name: Website
    if: inputs.web == 'true' && inputs.node_test == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Build
        shell: bash
        run: |
          pnpm build --filter=@pkrbt/cms
          pnpm build --filter=@pkrbt/web

      - name: Seed test data
        run: pnpm seed:dev

      - name: Start dev server
        run: pnpm start &

      - name: Install Playwright Browsers
        working-directory: ./apps/web
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm e2e --filter=@pkrbt/web

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: web-playwright-report
          path: ./apps/web/playwright-report/
          retention-days: 30
