name: Image

on:
  workflow_call:
    inputs:
      cms:
        type: string
        default: "false"
        description: build cms
      ref_name:
        type: string
        default: ${{ github.ref_name }}
        description: GitHub refname

jobs:
  cms:
    name: CMS
    if: inputs.cms == 'true'
    uses: paroki/pkrbt/.github/workflows/build-image.yml@next
    secrets: inherit
    with:
      name: CMS
      prefix: ghcr.io/paroki/pkrbt-cms
      dockerfile: apps/cms/Dockerfile
      target: prod
      goss_file: docker/goss-cms.yaml
      ref_name: ${{ inputs.ref_name }}
